[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
solc = "0.8.18"

[rpc_endpoints]
canto_testnet = "${CANTO_TESTNET_RPC_URL}"
#canto = "${CANTO_RPC_URL}"

# See more config options https://github.com/foundry-rs/foundry/tree/master/config